name: build
on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build images
        run: ./build.sh

      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-r86s
          path: bin/targets/x86/64/
