name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install libncurses5-dev libncursesw5-dev gettext xsltproc
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Download imagebuilder
        env:
          IMAGEBUILDER_URL: https://downloads.immortalwrt.org/releases/24.10.0/targets/x86/64/immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64.tar.zst
        run: |
          curl -L $IMAGEBUILDER_URL -o imagebuilder.tar.xz
          tar --zstd -xf imagebuilder.tar.xz --strip-components=1
          rm -f imagebuilder.tar.xz

      - name: Patch build config
        run: |
          sed -i '/CONFIG_ISO_IMAGES/d' .config
          sed -i '/CONFIG_VDI_IMAGES/d' .config
          sed -i '/CONFIG_GRUB_IMAGES/d' .config
          sed -i '/CONFIG_VHDX_IMAGES/d' .config
          sed -i '/CONFIG_VMDK_IMAGES/d' .config
          sed -i '/CONFIG_QCOW2_IMAGES/d' .config
          sed -i '/CONFIG_TARGET_ROOTFS_EXT4FS/d' .config

      - name: Build image
        run: make image FILES="files" PACKAGES="ip-full luci-app-homeproxy"

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-r86s
          path: bin/targets/x86/64/
