name: build
on: workflow_dispatch

env:
  VERSION: 23.05.2
  REPOSITORY: https://downloads.immortalwrt.org

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install libncurses5-dev libncursesw5-dev gettext xsltproc
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Download imagebuilder
        run: |
          curl -L $REPOSITORY/releases/$VERSION/targets/x86/64/immortalwrt-imagebuilder-$VERSION-x86-64.Linux-x86_64.tar.xz -o imagebuilder.tar.xz
          tar -Jxf imagebuilder.tar.xz --strip-components=1

      - name: Patch config
        run: |
          sed -i '/CONFIG_ISO_IMAGES/d' .config
          sed -i '/CONFIG_VDI_IMAGES/d' .config
          sed -i '/CONFIG_GRUB_IMAGES/d' .config
          sed -i '/CONFIG_VHDX_IMAGES/d' .config
          sed -i '/CONFIG_VMDK_IMAGES/d' .config
          sed -i '/CONFIG_QCOW2_IMAGES/d' .config
          sed -i '/CONFIG_TARGET_ROOTFS_EXT4FS/d' .config

      - name: Build images
        run: |
          make image FILES="files" PACKAGES="luci-app-homeproxy"

      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-r86s
          path: bin/targets/x86/64/
